version: '3'
services:
  app:
    build: .
    ports:
      - '3000:3000'
    restart: always
    depends_on:
      - db
  db:
    image: mysql:8.0.36
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '123456'
    ports:
      - '3306:3306'