version: '3.8'
services:
  api:
    container_name: api
    restart: "no"
    build: .
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - mongodb
    volumes:
      - .:/usr/src/app

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
    volumes:
      - mongodb_data:/data/db

volumes: 
  data: {}
