version: '3.8'
services:
  api:
    container_name: api
    restart: "no"
    build: .
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - db
    volumes:
      - .:/usr/src/app

  db:
    container_name: mongo
    restart: "no"
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - data:/data/db

volumes: 
  data: {}
